### ISSUE TITLE
Add custom classes to builder sections

### ISSUE THREAD

**Issue by MatthewEppelsheimer** [thethemefoundry/make#203]
How about exposing UI to add a custom class to a builder section, in this modal? http://cl.ly/image/3I0S1t3V1b1e

https://github.com/thethemefoundry/make/issues/56 is related, but doesn't go quite as far as I'd like.

I would be happy to work on a PR, but would like to clear this as a good direction, this first.

**Comment by danfascia** [comment]
This would greatly enhance the way I use Make as a child-theme developer.

Currently my CSS is very hard to go back to because the IDs are serialised and generated by Make, which is great that it does that but it results in a lot of "Code Inspector" sessions and a lot of CSS which makes no semantic sense - I depend on good comments!

Addition of user defined CSS selectors which are placed first in the class cascade (and that bit is really important!) would make front end styling much easier for developers.

**Comment by coreymckrill** [comment]
Custom values for both id and class attributes on the section wrapper have been implemented as an enhancement in version 1.6.0 of Make Plus.
