### ISSUE TITLE
Comment reply links disappear at 4th level

### ISSUE THREAD

**Issue by dknauss** [thethemefoundry/make#233]
The template for comments adds a nested "reply" link after each comment and the first 3 levels of nested replies under each comment. Starting with the fourth level of nested replies there is no longer any "reply" link. This means that comments intended as 4th+ level replies are not identified with a parent comment and are treated as a new 1st level comment without indentation below all other comments. 
- Comment (has reply link)
  - Reply 1 (has reply link)
    - Reply 2 (has reply link)
      - Reply 3 (has reply link)
      - Reply 4 (no reply link)

Replies at the 4th level and above should still have reply links following them that attach further comments to the parent comment ID. These comments won't be indented but will follow directly below the 3rd level comment.

**Comment by coreymckrill** [comment]
Confirmed, though I'm seeing the "reply" link on Depth 4, and it stops appearing on Depth 5. It looks like the markup is actually missing, so this isn't just a CSS issue. We'll investigate further.

Thanks @newlocalmedia

**Comment by coreymckrill** [comment]
@newlocalmedia it turns out that this is a function of the "Enable threaded comments X levels deep" setting in the Discussion Settings screen. The reply link markup won't be added for bottom-level comments or anything deeper. If you adjust the number, you can see the change.

This setting isn't currently tied to the style we've added in the theme that stops comments from indenting after level 4. We may need to look into addressing that.

**Comment by newlocalmedia** [comment]
Aha, that makes sense! I suppose the thing to do is just put in a very high value.

That is an odd setting -- it doesn't really stop people from commenting to reply to a thread; it just stops them from being able to do it the appropriate way.

**Comment by coreymckrill** [comment]
Changing this to "enhancement" since this is now about revisiting the comment indentation styles.
