### ISSUE TITLE
Open Sans doesn't work in sidebar or footer if other global font is selected

### ISSUE THREAD

**Issue by melissajohill** [thethemefoundry/make#265]
Yet other fonts seem to be working just fine. 

https://thethemefoundry.com/questions/topic/sidebar-fonts-open-sans-being-overwritten-by-global/#post-50745

**Comment by scottrrollo** [comment]
@coreymckrill 

**The problem**

When a user sets a **Global** font to anything other than **Open Sans**, the  **Sidebars &rarr; Widget Body** and the **Footer &rarr; Widget Body** Customizer options cannot be set to **Open Sans** — but can successfully be set to any other font choice.

**A solution**

I think the Customizer code is ignoring the **Open Sans** font because it's the theme's default. Because of this, the **Global** font is inherited and cannot be overrived. To fix this, the Customizer code should apply the `font-family` rule regardless of the font selected.

**Comment by coreymckrill** [comment]
^ @scottrrollo can you verify if this fixes the issue?

**Comment by scottrrollo** [comment]
@coreymckrill Looking good. Thanks! After looking again, the **Footer &rarr; Footer Text** Customizer option also needs to be fixed.

**Comment by coreymckrill** [comment]
Cool. Should be fixed there now too. Marking this as ready to deploy.

**Comment by coreymckrill** [comment]
Deployed in 1.6.6
