### ISSUE TITLE
Show/Hide Title in Page Edit screen not working correctly

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#321]
Cory,

I've been trying to show/hide the page title for pages on a staging site I'm working on.

https://totmerchres.staging.wpengine.com

Things seem to be a little wonky. Here are my steps:
1. I click in the Customizer to hide all page titles under Layout > Pages
2. I then go to the Page Editor for the specific page.
3. I unlock, then uncheck the hide box to show a title on a specific page.
4. I then relock the empty box.
5. I click update and check the page.
6. The Title is still hidden.

Here is a screen record of the issue: https://cl.ly/2J1G0O442F2K

I tried it reversed, so on Pages > Layout all pages would display the Title. I then tried to check the box to hide the title on the home page and it didn't work. I went back to the home page in the edit screen and saw that my selection was not saved.

I'm working in staging, so I can't imagine this is a caching issue.

**Comment by tonyzeoli** [comment]
I just tried it again and was able to hide the title by leaving the check box unlocked. Is that the correct functionality? Why if I try to lock the box after checking Hide Title does it clear the checkbox on Update?

**Comment by coreymckrill** [comment]
Hi @tonyzeoli !

The way it works is, if you've got all page titles hidden in _Layout > Pages_, then in order to show the page title on a particular page, you click the "unlink" icon and uncheck the box for _Hide page title_. Then click update.

So it sounds like you're taking an extra step here. You should not "relink" a layout setting after making a change to it, because this will cause it to change back to whatever the global setting is.

Does that help clear things up?

Sorry for the confusion here. We are still working on ways to improve this interface.
