### ISSUE TITLE
Set banner background image does not take

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#346]
I set an issue for banner background color already, then tried to set the banner background image and that does not take either.

Add background png:
See screenshot: https://cloudup.com/cUJ0gs-bfqf

Only see grey above/below/behind the banner.

Also, I'm using WP Engine staging, which has no cache, so that's not the issue.

**Comment by scottrrollo** [comment]
@tonyzeoli I have a hunch you're seeing this issue because you have **both** a background image and slide image set. If you remove those images from each slide, do you see your background image then?

Oh, and sorry we didn't get back to you earlier! Please always feel free to post these questions in our Help Center. We'll get back to you right away over there 😀

**Comment by tonyzeoli** [comment]
Sorry I didn't check back on this. I'll close this.
