### ISSUE TITLE
Add support for show / hide, modify author bio in Customize > Layout > Posts

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#367]
The author bio entered into the WordPress User Bio block is printing under the avatar and author name: https://savethegreatsouthbay.org/blog/fixing-habitats/united-by-water-the-cause-of-our-times/

Should have options to show / hide, font size, font weight, line height, font color, google font style.

This is a request for an enhancement.

**Comment by tomasstark** [comment]
Hey @tonyzeoli 👋

Poking around your page, it looks like that author box isn't a part of Make. It appears to be handled by a plugin called **WP - Author Box**. Is that correct? As it turns out, we can't offer Customizer style controls for third party plugins, sorry.

Since the author box is basically a part of your post content, it inherits styles and settings of your post. We recommend to use custom CSS to tweak its appearance.

Hope this helps! 🙂

**Comment by tonyzeoli** [comment]
Sorry, between the time I posted this and your note back, I hid the post
author bio with a line of CSS. It’s under the top referenced author avatar
at the top of the post, you just can’t see it because I hid it.

**Comment by tonyzeoli** [comment]
P.S. At the end of the day, there should be an option to show hide the
author bio, because if I leave the author avatar at the top of he post and
I want the bio at the bottom, there should be an option. An author bio can
be as short as one sentence or as long as infinity, so having he author bio
display automatically is not ideal.
