### ISSUE TITLE
Gutenberg conversion

### ISSUE THREAD

**Issue by TheDancingCode** [thethemefoundry/make#369]
Currently, the Make builder disables the Gutenberg editor. However, the Make components seem like ideal candidates for a conversion to Gutenberg blocks. Are there any plans to do this?

**Comment by scottrrollo** [comment]
@TheDancingCode Hey 👋 No plans just yet, sorry! We think the classic editor, which is used by Make's builder, is much better suited to complex designs than the Gutenberg editor. That's why we're giving people the options to switch over to Gutenberg for simple blog posts content, etc.

I hope that helps clear things up!
